-- Generated by Oracle SQL Developer Data Modeler 19.4.0.350.1424
--   at:        2020-05-24 22:29:28 MSK
--   site:      Oracle Database 11g
--   type:      Oracle Database 11g



CREATE TABLE actor (
    actor_name VARCHAR2(50) NOT NULL
);

ALTER TABLE actor ADD CONSTRAINT actor_pk PRIMARY KEY ( actor_name );

CREATE TABLE film (
    film_id  INTEGER NOT NULL,
    year     INTEGER,
    title    VARCHAR2(50)
);

ALTER TABLE film ADD CONSTRAINT film_pk PRIMARY KEY ( film_id );

CREATE TABLE film_actor (
    film_film_id      INTEGER NOT NULL,
    actor_actor_name  VARCHAR2(50) NOT NULL
);

ALTER TABLE film_actor ADD CONSTRAINT film_actor_pk PRIMARY KEY ( film_film_id,
                                                                  actor_actor_name );

CREATE TABLE likes (
    people_people_name  VARCHAR2(50) NOT NULL,
    actor_actor_name    VARCHAR2(50) NOT NULL
);

ALTER TABLE likes ADD CONSTRAINT likes_pk PRIMARY KEY ( people_people_name,
                                                        actor_actor_name );

CREATE TABLE people (
    people_name VARCHAR2(50) NOT NULL
);

ALTER TABLE people ADD CONSTRAINT people_pk PRIMARY KEY ( people_name );

ALTER TABLE film_actor
    ADD CONSTRAINT film_actor_actor_fk FOREIGN KEY ( actor_actor_name )
        REFERENCES actor ( actor_name );

ALTER TABLE film_actor
    ADD CONSTRAINT film_actor_film_fk FOREIGN KEY ( film_film_id )
        REFERENCES film ( film_id );

ALTER TABLE likes
    ADD CONSTRAINT likes_actor_fk FOREIGN KEY ( actor_actor_name )
        REFERENCES actor ( actor_name );

ALTER TABLE likes
    ADD CONSTRAINT likes_people_fk FOREIGN KEY ( people_people_name )
        REFERENCES people ( people_name );
